apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 261610780523.dkr.ecr.eu-central-1.amazonaws.com/votingapp-repo:worker
        name: worker
        imagePullPolicy: Always